version: '2'
services:
  conjur:
    image: registry.tld/conjur-appliance:4.9.13.0
    hostname: conjur
    security_opt:
      - label:seccomp:undefined
    environment:
      CONJUR_MASTER_HOSTNAME: "conjur.cyberark.local"
      CONJUR_MASTER_PASSWORD: "Cyberark1"
      CONJUR_MASTER_ORGACCOUNT: "PuppetDemo"
    volumes:
      - ./:/src:z
    security_opt:
      - seccomp:unconfined
    ports:
      - 443:443
      - 636
      - 5432
    restart: always

services:
  scope:
    image: weaveworks/scope:1.8.0
    network_mode: "host"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"
    restart: always

  puppet:
    image: my-puppet-enterprise:2017.3.1
    environment:
      AUTOSIGN: "true"
      TERM: "xterm"
      TZ: "UTC"
    hostname: puppet
    domainname: cyberark.local
    networks: 
      default: 
        aliases:
          - puppet.cyberark.local
    volumes:
      - ./puppet/manifests/:/etc/puppetlabs/code/environments/production/manifests/:Z
      - ./puppet/modules/motd/:/etc/puppetlabs/code/environments/production/modules/motd/:Z
    ports:
      - 1443:443
      restart: always
 
  prod-webapp:
    image: my-agentnode:1.0
    hostname: prod-webapp
    domainname: cyberark.local
    privileged: true
    restart: always

  dev-webapp:
    image: my-agentnode:1.0
    hostname: dev-webapp
    domainname: cyberark.local
    privileged: true
    restart: always

  cli:
    environment:
      CONJUR_ACCOUNT: PuppetDemo
      CONJUR_APPLIANCE_URL: https://conjur/api
    image: my-conjurcli:5.4.0
    volumes:
      - ./:/src:z
    hostname: conjurcli
    entrypoint: sleep
    command: infinity
    restart: always
